# Tema i3 iceberg — ventanas (gaps + bordes). Fuente: themes/iceberg.conf
# client.focused → border | background | text | indicator
gaps outer 2
gaps inner 2
smart_gaps on
for_window [class="^.*"] border pixel 2
for_window [class="Polybar"] border pixel 0
client.focused          #737373 #737373 #737373 #000000
client.urgent           #e27878 #5c3030 #161821 #000000
