gesture = 4, horizontal, workspace

gesture = 3, right, dispatcher, exec, ~/.config/hypr/scripts/move_focus.sh r
gesture = 3, left, dispatcher, exec, ~/.config/hypr/scripts/move_focus.sh l
gesture = 3, up, dispatcher, exec, ~/.config/hypr/scripts/move_focus.sh u
gesture = 3, down, dispatcher, exec, ~/.config/hypr/scripts/move_focus.sh d

gesture = 4, up, dispatcher, fullscreen
gesture = 4, down, dispatcher, togglefloating
