# Monitores y variables de entorno (sesión Wayland — blueman-manager al clic en applet).
# Mismos valores que shared/cnf-bin/config.toml [session.wayland]

env = PATH,$PATH:/usr/bin
monitor=eDP-1,preferred,auto,1
monitor=HDMI-A-2,preferred,auto,1

env = XCURSOR_SIZE,10
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland

permission = /usr/bin/hyprpm, plugin, allow
