# ================================================================== #
#             ESTÉTICA (redondeo, desenfoque, animaciones)           #
# ================================================================== #

decoration {
    rounding = 15   # 'corner-radius'

    blur {
        enabled = yes
        size = 2    # 'strength' en picom
        passes = 2
        new_optimizations = on
    }
}

animations {
    enabled = yes

    bezier = myBezier, 0.04, 0.8, 0.1, 1.04
    animation = windows, 1, 6, myBezier
    animation = windowsOut, 1, 6, default, popin 80%
    animation = border, 1, 9, default
    animation = fade, 1, 6, default
    animation = workspaces, 1, 5, default
}
