# ================================================================= #
#             APLICACIONES AL INICIO (exec-once / exec)             #
# ================================================================= #
 
exec = killall waybar; waybar &
exec = killall swww; swww-daemon &
exec-once = hypridle &
exec-once = pkill dunst; pkill mako; swaync &
exec-once = flameshot &
exec-once = copyq &
exec-once = hyprsunset &
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec = libinput-gestures-setup start &
exec-once = setxkbmap -layout us -variant intl

# Opcional: fondo estático con hyprpaper (comentado)
# exec-once = hyprpaper
