# Aplicaciones al inicio

exec-once = sleep 1 && killall -e xdg-desktop-portal-hyprland && killall xdg-desktop-portal && /usr/lib/xdg-desktop-portal-hyprland & sleep 2 && /usr/lib/xdg-desktop-portal &
exec-once = hyprpm reload -n
exec = killall waybar; waybar &
exec-once = copyq &
exec-once = killall hypridle; hypridle &
exec-once = killall ignis; ignis init &
exec-once = pkill dunst; pkill mako; swaync &
exec-once = hyprsunset &
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec = killall awww; awww-daemon &
exec = libinput-gestures-setup start &
exec-once = setxkbmap -layout us -variant intl
