# ================================================================== #
#             CONFIGURACIÓN GENERAL (gaps, bordes, layout)           #
# ================================================================== #

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
    col.active_border = rgba(005818ee) rgba(009e1aee) 45deg
    col.inactive_border = rgba(555555aa)

    layout = dwindle   # Alternativa a i3, similar a 'bsp'
}

windowrule = match:class com.github.hluk.copyq, float on, center on, size 800 600

