xwayland {
    force_zero_scaling = true
}

input {
    kb_layout = us
    kb_variant = intl
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        tap-to-click = true
    }

    sensitivity = 0.5
}

device {
    name = at-translated-set-2-keyboard
    kb_layout = us
}

device {
    name = "HID 04f3:0103"
    kb_layout = latam
    kb_options = lv3:ralt_switch
}

device {
    name = "chicony--hp-wired-desktop-320k-keyboard"
    kb_layout = latam
    kb_options = lv3:ralt_switch
}
