# ================================================================== #
#         CONFIGURACIÓN DE ENTRADA (teclado, touchpad, ratón)        #
# ================================================================== #

# Teclado en ingles csin teclas muertas

input {
    kb_layout = us
    kb_variant = intl
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        tap-to-click = true
    }

    sensitivity = 0.5   # -1.0 a 1.0, 0 por defecto
}
