# ================================================================= #
#             MONITORES Y VARIABLES DE ENTORNO                      #
# ================================================================= #

env = PATH,$PATH:/usr/bin

# Reemplaza eDP-1 con el nombre de tu pantalla (hyprctl monitors)
monitor=eDP-1,preferred,auto,1
monitor=HDMI-A-2,preferred,auto,1

# Variables de entorno para Wayland
env = XCURSOR_SIZE,10
env = QT_QPA_PLATFORMTHEME,qt5ct  # Para temas Qt
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
