# Hyprspace overview (hy3: sudo hyprpm disable hy3 && hyprpm reload -n)

plugin {
    overview {
        centerAligned = true
        onBottom = false
        panelHeight = 120
        workspaceMargin = 8
        drawActiveWorkspace = true
        affectStrut = false
        overrideGaps = false
    }
}
