# ================================================================= #
#                CONFIGURACIÓN PRINCIPAL DE HYPRLAND                #
# ================================================================= #

$mainMod = SUPER

source = ~/.config/hypr/conf.d/vars.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/exec.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/workspaces.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/gestures.conf
