# Configuración principal de Hyprland — incluye módulos desde conf.d/

source = conf.d/vars.conf
source = conf.d/monitors.conf
source = conf.d/exec.conf
source = conf.d/input.conf
source = conf.d/general.conf
source = conf.d/plugins.conf
source = conf.d/decoration.conf
source = conf.d/misc.conf
source = conf.d/workspaces.conf
source = conf.d/keybinds.conf
source = conf.d/gestures.conf
source = conf.d/theme.conf
