# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet --indicator
exec --no-startup-id blueman-applet
exec --no-startuo-id flameshot
exec --no-startup-id copyq

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

# Block the session
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lock.sh

# Touchpad configuration
exec_always --no-startup-id touchpad
exec_always --no-startup-id libinput-gestures-setup start
exec_always --no-startup-id libinput-gestures-setup restart

# Inicia los servicios de portal para permisos (micrófono, cámara, etc.)
exec --no-startup-id /usr/lib/xdg-desktop-portal
exec --no-startup-id /usr/lib/xdg-desktop-portal-gtk

# Starting the agent of Polkit of KDE for manage permissions
exec --no-startup-id /usr/lib/polkit-kde-authentication-agent-1

exec --no-startup-id dunst

# Set keyboard layout
exec_always --no-startup-id setxkbmap -layout us -variant intl
