bar {
    position top
    tray_output primary
    tray_padding 4
    # Barra: bumblebee-status/launch.sh (desplegado con deploy-configs.sh)
    status_command ~/.config/bumblebee-status/launch.sh
          colors {
            # background #222222ff
            background #222222
            statusline #eeeeee
            separator #666666
            #                    border  bakgr.  text
            focused_workspace   #005818 #00450b #ffffff
            active_workspace    #000445 #00450b #ffffff
            inactive_workspace  #000445 #555555 #888888
            urgent_workspace    #2f343a #900000 #ffffff
    }
}
