# Iniciar Polybar (commented, because we have bumblebee-status bar)
#exec_always --no-startup-id ~/.config/polybar/launch.sh

# Miselaneus
bindsym Control+Print exec flameshot full -c 
bindsym Print exec flameshot gui -c
bindsym $mod+Shift+t exec ~/.local/bin/toggle-keyboard.sh &
bindsym $mod+Shift+n exec ~/.config/eww/launch.sh &
