# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)

# Polybar: usar toggle-status-bar.sh polybar (conf.d/bar-mode/polybar.conf)
# exec_always --no-startup-id ~/.config/polybar/launch.sh &

