# Tema i3 classic — ventanas (gaps + bordes). Fuente: themes/classic.conf
gaps outer 2
gaps inner 2
smart_gaps on
for_window [class="^.*"] border pixel 2
for_window [class="Polybar"] border pixel 0
client.focused          #005818 #005818 #009e1a #009e1a
client.unfocused        #555555 #222222 #888888 #555555
client.focused_inactive #555555 #00450b #888888 #555555
client.urgent           #900000 #900000 #ffffff #900000
